[repository]
name = "hyprland-scroll-overview"
authors = ["yayuuu"]
commit_pins = [
    # Hyprland                                  hyprland-scroll-overview
    ["521ece463c4a9d3d128670688a34756805a4328f", "bd51b3d136b2c32540c460e18d7d0c6a63feb7f3"], # v0.54.3
]

[scrolloverview]
description = "A scrollable overview plugin for Hyprland."
authors = ["yayuuu"]
output = "scrolloverview.so"
build = [
    "make all",
]
