[repository]
name = "hyprland-scroll-overview"
authors = ["yayuuu"]
commit_pins = [
    # Hyprland                                  hyprland-scroll-overview
    ["521ece463c4a9d3d128670688a34756805a4328f", "5ca7928cfcf666212c8839005daff75aabe0ef22"], # v0.54.3
]

[scrolloverview]
description = "A scrollable overview plugin for Hyprland."
authors = ["yayuuu"]
output = "scrolloverview.so"
build = [
    "make all",
]
